- name: Update and upgrade APT packages
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
