- name: Update and upgrade APT packages
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Check installed upgrades
      shell: apt list --upgradable
      register: upgradable_packages
      changed_when: false

    - debug:
        msg: "{{ upgradable_packages.stdout_lines }}"

