- name: Install and configure NGINX
  hosts: all
  become: yes

  tasks:
  - name: Gather installed packages
    package_facts:
      manager: apt

  - name: Install NGINX if not present
    apt:
      name: nginx
      state: present
      update_cache: yes
    when: "'nginx' not in ansible_facts.packages"

  - name: Get checksum of deployed key
    stat:
      path: /home/{{ ansible_user }}/.ssh/id_rsa
      checksum_algorithm: sha1
    register: existing_key

  - name: Debug stat results - deployed
    debug:
      var: existing_key

  - name: Get checksum of local key
    local_action: stat path=../vault/id_rsa checksum_algorithm=sha1
    register: local_key
    become: yes

  - name: Debug stat results - local
    debug:
      var: local_key

  - name: Upload deploy key
    copy:
      src: ../vault/id_rsa
      dest: /home/{{ ansible_user }}/.ssh/id_rsa
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0600'
    when:
      - local_key.stat.exists
      - local_key.stat.checksum is defined
      - existing_key.stat.exists == false or
        (existing_key.stat.checksum is defined and existing_key.stat.checksum != local_key.stat.checksum)

  - name: Ensure GitHub is in known_hosts
    ansible.builtin.known_hosts:
      path: /home/{{ ansible_user }}/.ssh/known_hosts
      name: github.com
      key: "{{ lookup('pipe', 'ssh-keyscan -H github.com') }}"
      state: present
    become: false

  - name: Print current user
    ansible.builtin.command: whoami
    register: whoami_result
    changed_when: false

  - debug:
      var: whoami_result.stdout

  - name: Create /opt/static-site with correct permissions
    file:
      path: /opt/static-site
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0755'

  - name: Clone website repo
    become: false
    git:
      repo: git@github.com:Lunigan/nginx-website.git
      dest: /opt/static-site
      version: main
    register: clone_result

  - name: Log repo update
    debug:
      msg: "New commits pulled!"
    when: clone_result.changed

  - name: Show all handlers
    debug:
      var: ansible_playbook_handlers

  - name: Trigger handler manually
    debug:
      msg: "Triggering handler"
    notify: Restart nginx

  - name: Deploy Nginx config for site
    copy:
      src: /opt/static-site/nginx/default.conf
      dest: /etc/nginx/sites-available/default.conf
      owner: root
      group: root
      mode: '0644'
      remote_src: yes      
    notify: Restart nginx

  - name: Enable site
    file:
      src: /etc/nginx/sites-available/default.conf
      dest: /etc/nginx/sites-enabled/default.conf
      state: link
      force: yes
    notify: Restart nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
