- name: Install and configure NGINX
  hosts: all
  become: yes
  tasks:
  - name: Gather installed packages
    package_facts:
      manager: apt

  - name: Install NGINX if not present
    apt:
      name: nginx
      state: present
      update_cache: yes
    when: "'nginx' not in ansible_facts.packages"

  - name: Get checksum of deployed key
    stat:
      path: /home/{{ ansible_user }}/.ssh/id_rsa
      checksum_algorithm: sha1
    register: existing_key

  - name: Get checksum of local key
    local_action: stat path=vault/id_rsa checksum_algorithm=sha1
    register: local_key

  - name: Upload deploy key
    copy:
      src: vault/id_rsa
      dest: /home/{{ ansible_user }}/.ssh/id_rsa
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0600'
    when: existing_key.stat.checksum != local_key.stat.checksum

  - name: Clone website repo
    git:
      repo: git@github.com:Lunigan/nginx-website.git
      dest: /opt/static-site
      version: main
    register: clone_result

  - name: Log repo update
    debug:
      msg: "New commits pulled!"
    when: clone_result.changed

  - name: Deploy Nginx config for site
    copy:
      src: /opt/static-site/nginx/default.conf
      dest: /etc/nginx/sites-available/my-website.conf
      owner: root
      group: root
      mode: '0644'
    notify: Restart nginx

  - name: Enable site
    file:
      src: /etc/nginx/sites-available/my-website.conf
      dest: /etc/nginx/sites-enabled/my-website.conf
      state: link
      force: yes
    notify: Restart nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
