- name: Enable passwordless sudo for Ansible
  hosts: all
  become: yes
  tasks:  
    - name: Check if passwordless sudo is configured
      shell: "grep -r 'NOPASSWD' /etc/sudoers.d || echo 'Not found'"
      register: sudo_status
      changed_when: false

    - name: Ensure sudoers.d directory exists
      file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'

    - name: Allow passwordless sudo for ansible user
      lineinfile:
        path: /etc/sudoers.d/ansible-nopasswd
        create: yes
        state: present
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: '/usr/sbin/visudo -cf %s'
        mode: '0440'
      when: "'NOPASSWD' not in sudo_status.stdout"