- import_playbook: apt_upgrade.yml
- import_playbook: ufw_setup.yml

- name: Initial Setup for Ubuntu Server
  hosts: all
  become: true
  roles:
    - role: sudoers_config
      sudoers_user: "{{ ansible_user }}"
  tasks:
    - name: Install Net-Tools
      apt:
        name: net-tools
        state: present
        update_cache: yes
    - name: Install htop
      apt:
        name: htop
        state: present
        update_cache: yes