- import_playbook: apt_upgrade.yml
- import_playbook: ufw_setup.yml

- name: Initial Setup for Ubuntu Server
  hosts: all
  become: true
  tasks:
    - name: Gather installed packages
      package_facts:
        manager: apt

    - name: Install missing tools
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - net-tools
        - htop
        - unattended-upgrades
        - fail2ban
      when: "item not in ansible_facts.packages.keys()"

    - name: Disable SSH login for root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: Restart SSH

    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH

    - name: Enable periodic security updates
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
        owner: root
        group: root
        mode: '0644'

    - name: Reconfigure unattended-upgrades
      command: dpkg-reconfigure -f noninteractive unattended-upgrades
      when: "'unattended-upgrades' in ansible_facts.packages"

    - name: Ensure fail2ban is running and enabled
      service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Configure fail2ban for SSH
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [sshd]
          enabled = true
          port    = ssh
          filter  = sshd
          logpath = /var/log/auth.log
          maxretry = 5
          bantime = 3600
        owner: root
        group: root
        mode: '0644'
      notify: Restart fail2ban

  handlers:
  - name: Restart SSH
    service:
      name: ssh
      state: restarted
      
  - name: Restart fail2ban
    service:
      name: fail2ban
      state: restarted
