- import_playbook: apt_upgrade.yml
- import_playbook: ufw_setup.yml

- name: Initial Setup for Ubuntu Server
  hosts: all
  become: true
  roles:
    - role: sudoers_config
      sudoers_user: "{{ ansible_user }}"
  tasks:
    - name: Gather installed packages
      package_facts:
        manager: apt

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install missing common tools
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - net-tools
        - htop
      when: "item not in ansible_facts.packages.keys()"
