- name: Install and configure UFW on all hosts
  hosts: all
  become: yes
  vars:
    ufw_rules:
      - { rule: allow, name: OpenSSH }
      - { rule: allow, port: 80, proto: tcp }
      - { rule: allow, port: 443, proto: tcp }
      - { rule: deny, direction: in }
  tasks:
  - name: Gather installed packages
    package_facts:
      manager: apt

  - name: Install UFW if not present
    apt:
      name: ufw
      state: present
      update_cache: yes
    when: "'ufw' not in ansible_facts.packages"

  - name: Simulate each UFW rule
    community.general.ufw:
      rule: "{{ item.rule }}"
      name: "{{ item.name | default(omit) }}"
      port: "{{ item.port | default(omit) }}"
      proto: "{{ item.proto | default(omit) }}"
      direction: "{{ item.direction | default(omit) }}"
    loop: "{{ ufw_rules }}"
    check_mode: yes
    register: rule_checks

  - name: Apply required UFW rules
    community.general.ufw:
      rule: "{{ item.rule }}"
      name: "{{ item.name | default(omit) }}"
      port: "{{ item.port | default(omit) }}"
      proto: "{{ item.proto | default(omit) }}"
      direction: "{{ item.direction | default(omit) }}"
    when: rule_checks.results[loop.index0].changed
    loop: "{{ ufw_rules }}"
    loop_control:
      label: "{{ item.name | default(item.port | string) }}"

  - name: Check if UFW is enabled
    command: ufw status
    register: ufw_status
    changed_when: false
    failed_when: false

  - name: Enable UFW
    ufw:
      state: enabled
    when: "'inactive' in ufw_status.stdout"